config/routes.rb
Rails.application.routes.draw do
  resources :people
  root 'people#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # before_action : find_person, only: [:show, :edit, :update]

  def index
    @people = Person.all.order("created_at DESC")
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to @person
    else
      render 'new'
  end
end

def show
  @person = Person.find(params[:id])
end

def edit
  @person = Person.find(params[:id])
end

def update
  @person = Person.find(params[:id])

  if @person.update(person_params)
    redirect_to @person
  else
    render 'edit'
  end
end

def destroy
  @person = Person.find(params[:id])
  @person.destroy
  redirect_to root_path
end

private

  def person_params
    params.require(:person).permit(:Name, :Age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrailProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", root_path %> &nbsp&nbsp&nbsp&nbsp&nbsp
    <%= link_to "Add Details", new_person_path %>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
  <%= f.label :Name %><br>
  <%= f.text_field:Name %><br>
  <br>
  <%= f.label :Age %><br>
  <%= f.text_field:Age %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/people/edit.html.erb
<h1>Edit Person Details</h1>

<%= render 'form'%>

app/views/people/index.html.erb
<% @people.each do |person|%>
<h2><%= person.Name %></h2>
<div><%= person.Age %></div>

<%= link_to "Read Person", person %>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form'%>

app/views/people/show.html.erb
<br>
<br>
<br>
<div style="width:95%;margin: 0 auto;">
<span>Name: <h4 style="display: inherit;"><%= @person.Name %></h5></span><br>
<span>Age: <p style="display: inherit;"><%= @person.Age %></p></span><br><br>
<%= link_to "Edit Details", edit_person_path(@person) %> &nbsp&nbsp
<%= link_to "Delete Details", person_path(@person), method: :delete, data: {confirm: "Are you sure ?"} %>
</div>